### ISSUE TITLE
Tour para iniciantes no sistema

### ISSUE THREAD

**Issue by rrrcompagnoni** [castsbrasil/castsbrasil#214]
vamos discutir como vai funcionar isso?

**Comment by plribeiro3000** [comment]
@rrrcompagnoni Você pode descrever melhor o que é essa feature e qual a sua opinião?

**Comment by rrrcompagnoni** [comment]
@plribeiro3000  opa, na realidade eu fiz o login no site 
tem o ver screencasts, submeter um cast e o ser iniciado e vi que só tem um void no js
a ideia era discutir como vai funcionar esse 'tutorial'

**Comment by mfbmina** [comment]
@rrrcompagnoni quando li "ser iniciado" pensei que você queria criar uma seita! hahahaahaha mas o que acham de pequenos videos mostrando funcionalidades do sistema? Como por exemplo um video-tutorial para postar um video, outro para alterar o perfil.

**Comment by plribeiro3000** [comment]
A gente ja falou um pouco sobre isso antes [aqui](https://github.com/RubyCastsBrasil/RubyCastsBrasil/issues/51).

Temos essa página na wiki: [Motivações](https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Motivacoes) e [Como fazer um bom cast](https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Como-fazer-um-bom-cast).

Acho que a gente ja discutiu sobre isso também mas não consegui achar um link. Acredito que posso ter esquecido de mover pro wiki. =s

**Comment by rrrcompagnoni** [comment]
HUHUHUHAUA tbm pensei isso quando vi no site

**Comment by mfbmina** [comment]
@plribeiro3000 fiquei confuso aqui... qual a ligação entre as "motivações" e o com o "ser iniciado". O segundo me remete a aprender sobre o sistema e o primeiro sobre o porque eu deveria utilizar o sistema.

**Comment by plribeiro3000** [comment]
É como eu disse. É relacionado. A gente começou a discutir sobre isso e daí o link no site.

Se me recordo bem, o que havia se falado sobre é que a gente teria um tutorial no estilo do de `Como fazer um bom cast` explicando sobre o sistema e a gente teria uma página no site com esse texto ou linkaria para uma página no wiki (temporariamente) assim como já fizemos com outras.

Achei a issue que eu comentei anteriormente: https://github.com/RubyCastsBrasil/RubyCastsBrasil/issues/52

**Comment by mfbmina** [comment]
Saquei @plribeiro3000 ! Acho que rola sim escrevermos os tutoriais neste estilo, porém gosto muito da idéia de um screencast tutorial pra criar screencasts.. tipo screencast inception! haha

**Comment by plribeiro3000** [comment]
Acho que a idéia de um cast é legal. Eu tinha pensado anteriormente em usar o [bootstraptour](http://bootstraptour.com/) também porque fica mais ativo do lado do usuário. 

Mas acho que isso é algo que rola ter depois de a gente definir pelo menos um documento em texto do passo a passo. Antes fica muito na especulação. Acho que a gente pode marcar isso do cast ou tour como uma funcionalidade para a próxima versão. Que tal?

**Comment by mfbmina** [comment]
Maneiro demais esse bootstraptour! Não conhecia não! Mas concordo com escrevermos um guia antes sim. Isso vai ser útil até como roteiro do que colocar no screencast ou na decisão que chegarmos!

**Comment by plribeiro3000** [comment]
O maneiro do bootstraptour é que ele não precisa nem ser steps na mesma página. Se for preciso ele leva o usuário para a próxima página e traz de volta. =)

**Comment by mfbmina** [comment]
Vi mesmo! Muito legal a parada!

**Comment by wenderjean** [comment]
Curti demais esse bootstraptour galera, não conhecia tbm não. Vocês acham que daria ora unir as duas coisas, videos e bootstrap tour ou poluiria demais a experiencia do usuário? De repente só o bootstraptour mata a charada.

**Comment by rrrcompagnoni** [comment]
malz ai galera, tava no rio sem note :T
vou ver o bstour

**Comment by mfbmina** [comment]
@wenderjean acho que depende da forma que fizermos! Se for bem feito vai ficar bom demais

**Comment by rrrcompagnoni** [comment]
https://github.com/schneems/wicked
alguém já usou/viu?

**Comment by mfbmina** [comment]
@rrrcompagnoni nunca vi não. Já chegou a usar?

**Comment by rrrcompagnoni** [comment]
@mfbmina eu comecei a usar em um checkout
mas não cheguei a terminar, não é tão complicado

**Comment by rrrcompagnoni** [comment]
eu imaginava algo do tipo o cara vai criando e recebendo instruções ao mesmo tempo

**Comment by plribeiro3000** [comment]
@rrrcompagnoni A idéia não é so para criação/edição mas para todo o processo. Desde listar os casts, filtrar por preferências, comentar e explicar como a gamificação funciona. Por isso que eu acredito que o `wicked` não sirva para o proposto.

Para a criação pode até ser mas por agora só temos 3 campos dae nem faz muito sentido.

**Comment by rrrcompagnoni** [comment]
a, tranquilo :D

**Comment by plribeiro3000** [comment]
Alguém tem algo pra adicionar aqui?

**Comment by pragmaticivan** [comment]
Acho que rola fechar essa amanhã?

**Comment by plribeiro3000** [comment]
@pragmaticivan Fechando tu passa a decisão pro wiki? Ou se não me avisa que eu passo. =)

**Comment by plribeiro3000** [comment]
Galera, só pra fechar isso aqui. Apareceram 2 idéias que se remetem mais ao que estamos querendo:

* screencast ensinando a usar o sistema
* bootstraptour
* as 2 opções acima

Tem também a idéia do @rrrcompagnoni sobre usar a gem wicked mas acha que ela não encaixa muito pro caso em que estamos querendo resolver.

Vou deixar essa discussão em aberto mais uns dias para votação.

PS: @rrrcompagnoni A gente pode usar a gem wicked em outros casos. Ela é bem massa. =)

**Comment by plribeiro3000** [comment]
Eu acho que se fizermos algo bem feito ficaria legal ter os dois.
Um screecast ensinando a navegar pelo sistema e o bootstraptour para mostrar as features, como mostrar onde fica os dados do autor e essas outras coisas. =)

Mas por agora minha opinião é para ficarmos com o bootstraptour por ser mais simples de entregar.

**Comment by plribeiro3000** [comment]
Galera, mandem seu votos. ehheheh (menos de 1 minuto)

Isso aqui é democracia, se tiver só  voto meu vai parecer tirania. uaheuhauehuaheuaheuh

**Comment by wenderjean** [comment]
Eu voto bootstraptour  :)

**Comment by rrrcompagnoni** [comment]
vamos de bootstraptour :p

**Comment by mfbmina** [comment]
bootstraptour! :smile:
