### ISSUE TITLE
Projeto morreu?

### ISSUE THREAD

**Issue by orafaelfragoso** [castsbrasil/castsbrasil#259]

**Comment by juuh42dias** [comment]
Está sofrendo com um hiato...

O projeto está de pé, porém infelizmente boa parte dos colaboradores está bastante ocupados com outras atividades :"(

Mas o projeto está total aberto pra contribuições <3

**Comment by plribeiro3000** [comment]
@orafaelfragoso Morto não está mas está desativado por falta de contribuidores. rs

Temos algumas issues em aberto. 😸

**Comment by orafaelfragoso** [comment]
@plribeiro3000 @juuh42dias Eu até sinto vontade de contribuir, mas atualmente tem tantas opções de tecnologia que podem substituir esse monolito, que fico até incomodado.

Pra layout não precisamos mais de PSD, temos o Figma aí...
Podemos desacoplar o front utilizando React também...
Transformar o projeto numa API...

Estou aberto pra trocar uma idéia.

**Comment by plribeiro3000** [comment]
@orafaelfragoso O ponto real é a necessidade de transformar esse projeto em algo mais complexo que precisa ser. =)

Entendo sua desmotivação e talvez esse não seja o projeto que está buscando contribuir no momento.

A idéia aqui é facilitar a entrada de novas pessoas no mundo re ruby e ruby on rails. Utilizar de uma SPA ou um front separado só irá aumentar a complexidade do sistema sendo que o bom e velho rails monolito funciona muito bem. Considerando que nunca tivemos nenhum contribuidor ativo além daqueles que de fato vem mantendo o projeto de pé desde o início minha preocupação é de `over engineering` e depois ficar para alguém manter isso sozinho.

Quanto a idéia do Figma eu acho que não tem problema. 

PS: Se a comunidade voltar a contribuir para o projeto e a gente voltar a ter contribuidores ativos, acho muito válido rediscutirmos a arquitetura do projeto.

**Comment by orafaelfragoso** [comment]
@plribeiro3000 Boa!
